### PR TITLE
Flesh out readme for wasp

### PR DESCRIPTION
**Pull request by balbuf**

### CODE REVIEW

**Comment by kangabell** [comment]
@balbuf wow very interesting project! Readme looks great. Only criticism is mixing the case of the text (e.g. "wasp" vs. "Wasp", or "twig" instead of "Twig"). Seems nitpicky though so I'm calling this approved!!!!

**Comment by balbuf** [comment]
Thanks @kangabell ! I _think_ I've only capitalized "wasp" when it is the first word of a sentence, otherwise it should be stylized in lowercase. As for Twig, it looks like they do stylize that in title case wherever it is used, so I'll fix that.

**Comment by balbuf** [comment]
Then again, maybe we should just treat "wasp" like a proper noun everywhere... Anyway, I've updated the "twig" references! @kangabell

**Comment by kangabell** [comment]
@balbuf okie doke! approved : )

**Pull request merged**
